### ISSUE TITLE
Instruction for building a release doesn't match current workflow

### ISSUE THREAD

**Issue by ApolloZhu** [jteng2/CSE-403-RecipeCart#40]
Currently the website is deployed using python, but the developer documentation says building a release is the step is the same as making a normal build. Please provide the exact steps to make a release so anyone can replicate the setup.

**Comment by CharlesAtUW** [comment]
This commit (done before midnight) addresses this:
https://github.com/jteng2/CSE-403-RecipeCart/pull/43/commits/fbc2bc917bfdb967c1790fdf275857cd2701f081
